### ISSUE TITLE
Progressinator

### ISSUE THREAD

**Issue by ZwickerZ** [ZwickerZ/interactive-polaroids#1]
The progress page of learn-the-web is giving me a 0 for this assignment, with Markbot calling me a cheater. What did I do?? @charlie-quinn

**Comment by charlie-quinn** [comment]
Looks like you accidentally rotated the screenshot provided so Markbot thinks you `cheated`.

The code looks good to me! I've manually updated this mark. 🤖✅

**Comment by charlie-quinn** [comment]
⚠️`Reminder: please close this issue once it has been resolved.`
